### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [jr-consulting/kodilla-js8.6-repository#1]
- [x] dorzucilem jeden commit - zobacz jak kod powinien byc sformatowany dla lepszej czytelnosci (wciecia obowiazuja w js podobnie jak w html i css)
- popraw jak poprzednio `<title> Tytul strony </title>` i `<link rel="stylesheet" href="css/style.css">`
- wywolaj funkcje wewnatrz console.log z jakimis liczbami
- wyswietl zawartosci trzech zmiennych `triangle...` za pomoca console.log'a

**Comment by jr-consulting** [comment]
done. Czy to o to chodziło w js?

**Comment by zdolny** [comment]
tak, z js-em o to chodzilo
Pozwolilem sobie na drobne poprawki (zpulluj sobie moje zmiany)
jest ok
